  version: "3.8"
  services: 
        csd:
            container_name: ticketsApp
            restart: always
            build: .
            ports: 
              - "5000:3000"
            links:
              - mongo
            volumes:
              - .:/usr/src/app
        mongo:
            container_name: mymongodatabase
            image: mongo
            volumes: 
              - /data/mymongodatabase       
            ports:
              - "27018:27017"
